# menus.toml

[[main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
[[main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = 10
[[main]]
        identifier = "members"
        name = "Members"
        url = "/members/"
        weight = 10
[[main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
        weight = 10
